# Developer https://t.me/IBoTuS

sound:
  #Звук при подборе предметов в шалкер
  sound-pickup: ENTITY_ITEM_PICKUP:0.3:1.0 #Название звука/Громкость/Темп
  #Звук если игрок в бою пытается открыть шалкер
  sound-combat: BLOCK_NOTE_BLOCK_BASS:1.0:1.0 #Название звука/Громкость/Темп

shulker-inventory:
  #Включить/Выключить всасывания ресурсов в пустой шалкер игрока
  enabled: true
  #Какие шалкера будут всасывать ресурсы
  whitelist-shulker: [SHULKER_BOX, WHITE_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, GRAY_SHULKER_BOX, BLACK_SHULKER_BOX, BROWN_SHULKER_BOX, RED_SHULKER_BOX, ORANGE_SHULKER_BOX, YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, GREEN_SHULKER_BOX, CYAN_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX, BLUE_SHULKER_BOX, PURPLE_SHULKER_BOX, MAGENTA_SHULKER_BOX, PINK_SHULKER_BOX]
  #Какие предметы не будет всасывать шалкер
  blacklist-items: [SHULKER_BOX, WHITE_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, GRAY_SHULKER_BOX, BLACK_SHULKER_BOX, BROWN_SHULKER_BOX, RED_SHULKER_BOX, ORANGE_SHULKER_BOX, YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, GREEN_SHULKER_BOX, CYAN_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX, BLUE_SHULKER_BOX, PURPLE_SHULKER_BOX, MAGENTA_SHULKER_BOX, PINK_SHULKER_BOX]

shulker-open:
  #Включить/Выключить открытия шалкеров при клике правой кнопки мыши шалкером по воздуху
  enabled: true
  #Разрешить/Запретить открытие шалкеров в бою
  enable-in-combat: true
  #Сообщение при открытии шалкера если игрок в бою
  shulker-combat-message: "#0EC8E2[✘] &7| &fВы не можете открыть шалкер, пока вы в бою"
  #Какие шалкера будут открываться при клике правой кнопки мыши шалкером по воздуху
  shulker-list: [SHULKER_BOX, WHITE_SHULKER_BOX, LIGHT_GRAY_SHULKER_BOX, GRAY_SHULKER_BOX, BLACK_SHULKER_BOX, BROWN_SHULKER_BOX, RED_SHULKER_BOX, ORANGE_SHULKER_BOX, YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, GREEN_SHULKER_BOX, CYAN_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX, BLUE_SHULKER_BOX, PURPLE_SHULKER_BOX, MAGENTA_SHULKER_BOX, PINK_SHULKER_BOX]
